FROM        docker.io/redhat/ubi9:latest
ADD         sample.txt /
ADD    --keep-git-dir     https://github.com/raghudevopsb87/learn-docker.git /
ADD    --unpack=true     https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip /
