FROM        docker.io/redhat/ubi9:latest
ADD         sample.txt /
ADD    --keep-git-dir     https://github.com/raghudevopsb87/learn-docker.git /
ADD    --unpack=true     https://dlcdn.apache.org/httpd/httpd-2.4.66.tar.gz /
